tests for projects endpoint
SELab-2/OSOC-4 pull request #314
Opened 2022-04-23 21:43 UTC by Vital7788

2022-05-01 20:54 UTC, StefVdHaute requested changes
I noticed a lot of your code is duplicated. Some general tips i would like you to implement:
1. You often use the same arguments for mock projects. You can save the arguments in a dict in the class and reuse them by using `Project(**the_arg_dict)`, this dict can also be used for your request body's.
2. If you want to seperate tests of different users don't write the tests twice. Write the test for 1 user (ex. user_admin) and generalize it so you could pass the users with equal access rights you want to test for to the testcode.
3. Your checks are very similar to the point my IDE gives warnings for multiple 20+ line blocks of duplicated code. Create a check function.

Lastly check my previous request for change.

2022-05-01 20:54 UTC, StefVdHaute commented on backend/app/tests/test_routers/test_projects.py
> +        project_coach = await read_where(User, User.role == UserRole.COACH, session=self.session)
There are multiple coaches in the testdata. Use get_user_by_name("user_approved_coach") or make read_where more detailed by checking whether user is active, approved and not disabled.

2022-05-01 20:54 UTC, StefVdHaute commented on backend/app/tests/test_routers/test_projects.py
> +        self.assertEqual(str(project_in_db.id), project_id, f"Project id of '{project_name}' in the response url is not same as it in the database.")
You made a sentence structure mistake. Consider `f"Project id of '{project_name}' in the response URL is not equal to the id found in the database."`.

2022-05-01 20:54 UTC, StefVdHaute commented on backend/app/tests/test_routers/test_projects.py
> +        self.assertEqual(len(project_skills_in_db), len(skills), f"Not all skills have not been added for project {project_name}")
Double negation in sentence.

2022-05-04 22:09 UTC, Vital7788 commented
requested changes have been made

2022-05-04 23:42 UTC, Vital7788 commented
> I noticed a lot of your code is duplicated. Some general tips i would like you to implement:
> 
>     1. You often use the same arguments for mock projects. You can save the arguments in a dict in the class and reuse them by using `Project(**the_arg_dict)`, this dict can also be used for your request body's.
> 
>     2. If you want to seperate tests of different users don't write the tests twice. Write the test for 1 user (ex. user_admin) and generalize it so you could pass the users with equal access rights you want to test for to the testcode.
> 
>     3. Your checks are very similar to the point my IDE gives warnings for multiple 20+ line blocks of duplicated code. Create a check function.
> 
> 
> Lastly check my previous request for change.

For your second point, I think having a single test to test all possible users makes the tests much harder to read and understand. Additionally, it's often not possible to generalize tests like that since multiple coaches could have access, but have different responses depending on which editions/projects they have access to.

All the other changes have been implemented.

2022-05-05 12:19 UTC, Vital7788 reviewed
looks good to me

2022-05-05 12:20 UTC, merged