Add project
SELab-2/OSOC-4 pull request #437
Opened 2022-05-07 13:19 UTC by thabils

Clean up of add project

2022-05-08 08:28 UTC, SimonVandeVyver requested changes
The add admin/coach to project does not work, pushing the '+' button saved the project when I tested. 
Check if the essential fields are not empty before saving a project. I was able to add a project with empty title. I'm not sure if this is a problem, if it is no problem for the backend that the title is empty, you can ignore this comment.
The 'delete project' does not work yet, but maybe that is for another pr?
Besides that, the UI works well, but I have a few layout remarks.
The page does not have enough margin on the sides. There must be bigger margins on the left and the right. 
Add more vertical space between the input fields.
I think the title 'New project" should be on the left, then it is consistent with the rest of the application.
The alignment is not perfect: The skill selector and '+' button should have the same left margin as the other subtitles and input fields.
The alignment for adding the users is also not perfect.

2022-05-19 14:55 UTC, thabils commented
> The add admin/coach to project does not work
 The 'delete project' does not work yet, but maybe that is for another pr? 
Both of these will be addressed in different pr's all the other remarks should be fixed.

2022-05-19 18:39 UTC, QuintenVervynck requested changes
removing a required skill doesn't work as expected

2022-05-20 06:33 UTC, SimonVandeVyver approved these changes

2022-05-20 12:50 UTC, QuintenVervynck approved these changes

2022-05-20 12:54 UTC, merged