Tests for editions and suggestions routers
SELab-2/OSOC-4 pull request #446
Opened 2022-05-09 00:24 UTC by Vital7788

2022-05-14 13:36 UTC, StefVdHaute commented
@Vital7788 When will this pull request be ready. I need the ProjectGenerator for testing the next largest router (Participation tests).

2022-05-19 06:23 UTC, Vital7788 commented
Tests have been updated and #522 has been fixed.

2022-05-19 08:50 UTC, StefVdHaute requested changes
Coverage for the editions router is 65% this is too low.
There also was a recent push to add more documentation to the backend, tests are included in this so docstrings for the test functions would be appreciated, other test classes will soon also have docstrings..

2022-05-19 08:50 UTC, StefVdHaute commented on backend/app/tests/test_base.py
> +        self.user_coach = self.users["coach"]
What is this for?

2022-05-19 08:50 UTC, StefVdHaute commented on backend/app/tests/test_routers/test_suggestions.py
> +        await update(project, self.session)
Shouldn't everything in this function up to this line be done in `asyncSetup()`?

2022-05-19 08:50 UTC, StefVdHaute commented on backend/app/tests/utils_for_tests/ProjectGenerator.py
> +    def generate_project(self):
Add a year variable so we can generate projects in different editions.

2022-05-19 08:50 UTC, StefVdHaute commented on backend/app/tests/utils_for_tests/QuestionTagGenerator.py
> +    def generate_question_tags(self, n=1):
Add a year variable so we can generate QuestionTags in different editions.

2022-05-19 08:50 UTC, StefVdHaute commented on backend/app/tests/utils_for_tests/QuestionTagGenerator.py
> +                mandatory=True,
Not sure whether generating mandatory tags like this is a good idea. I think it would be better for the mandatory QuestionTags to be hardcoded as they are now.

2022-05-19 08:50 UTC, StefVdHaute commented on backend/app/tests/test_routers/test_editions.py
> +class TestEditions(TestBase):
Why not setup data in `asyncSetup()`? If the reason is because the data for the different tests is too different you may split up this class in different classes or move at least a subset like `create_edition_in_db()` to `asyncSetup()`.

2022-05-19 08:54 UTC, StefVdHaute commented
I forgot to mention this in the review but i'd also like to ask that when you create a DataGenerator you also use this Generator in ddd to make ddd more readable and easier to change.

2022-05-20 01:00 UTC, Vital7788 commented on backend/app/tests/test_routers/test_editions.py
> +class TestEditions(TestBase):
I've moved `create_edition_in_db()` to `asyncSetup()`, but it doesn't make any sense to do anything similar for other data since there is so little overlap.

2022-05-20 04:26 UTC, Vital7788 commented
Increasing code coverage will be done in another PR.
Other requested changes have been made.

2022-05-20 08:28 UTC, StefVdHaute approved these changes
Everything look's good, would you just add documentation to the 2 new Generators? You can look at the documentation [in development](https://github.com/SELab-2/OSOC-4/tree/development/backend/app/tests/utils_for_tests) for an example.

2022-05-20 21:29 UTC, merged