add new users to the latest edition
SELab-2/OSOC-4 pull request #519
Opened 2022-05-18 15:20 UTC by StefVdHaute

2022-05-18 16:20 UTC, QuintenVervynck requested changes

2022-05-18 16:20 UTC, QuintenVervynck commented on backend/app/routers/editions.py
> +    return await read_where(Edition, Edition.year == year, session=session)
you query the db twice while you could do it in one query + sorting like we did on the other places we needed the current edition.

What is the advantage of doing it like this?

2022-05-19 09:17 UTC, StefVdHaute commented on backend/app/routers/editions.py
> +    return await read_where(Edition, Edition.year == year, session=session)
There is no advantage i just didn't think of it, i'll change it

2022-05-19 09:44 UTC, QuintenVervynck approved these changes
looks good now!  fix that flake8 and merge

2022-05-19 09:45 UTC, QuintenVervynck commented
owh it's gone already

2022-05-19 09:45 UTC, QuintenVervynck commented
tests do fail but I'll leave that up to you if you want to merge or not

2022-05-19 09:46 UTC, StefVdHaute commented
I don't know why the tests fail, I'll look into that but locally they worked.

2022-05-19 09:57 UTC, merged