Change email
SELab-2/OSOC-4 pull request #568
Opened 2022-05-20 13:17 UTC by Jarne-Andries

2022-05-21 09:52 UTC, SimonVandeVyver requested changes
When you input a new email-address, it is not checked if this is your email address and if it is a valid email address. I could input 'dfmqjdmfqj@ugent.be' and the change of email was applied.
Maybe we could send an email to the new email address to approve the changes. Untill this is approved, the email address should not change in the database.

2022-05-21 19:54 UTC, Jarne-Andries commented
I've added a validate email input that makes sure the given email is correct

2022-05-22 08:15 UTC, SimonVandeVyver submitted a review, later dismissed
I made a new account and pushed "request new emailaddress", I got the toast error "something went wrong". 
The post failed with a 404
![image](https://user-images.githubusercontent.com/99675815/169685418-a367c80c-630a-4292-93c7-4d54af765755.png)

2022-05-22 09:05 UTC, SimonVandeVyver approved these changes

2022-05-22 09:05 UTC, merged