Project details and new project layout fix
SELab-2/OSOC-4 pull request #577
Opened 2022-05-20 21:33 UTC by thabils

fixed small layout issues
fixed error messages

2022-05-21 07:29 UTC, SimonVandeVyver requested changes
When editing a project and adding a new required skill, the skill selector does not work.

2022-05-21 12:23 UTC, SimonVandeVyver requested changes
In the file `Inputchecker.js`, there is an "if... else if... else if... else" construction which has many times "else if". i don't think this is a good code style. 
You could create a list [body.name, body.description, body.partner_name, body.partner_description] and a list ["name", "project description", ...] to write 
if (list.some(...)) {
    response.problem = otherlist[list.indexOf(...)]
}
With this construction the if construction will not be so big.

2022-05-22 07:07 UTC, QuintenVervynck approved these changes

2022-05-22 07:11 UTC, SimonVandeVyver approved these changes

2022-05-22 07:11 UTC, merged